//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molodykh_Potolki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int код_заказа { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public int код_клиента { get; set; }
        public int срок_дни { get; set; }
        public Nullable<System.DateTime> дата_изготовления { get; set; }
        public Nullable<System.DateTime> дата_монтажа { get; set; }
        public Nullable<decimal> сумма_потолка { get; set; }
    
        public virtual Клиент Клиент { get; set; }
    }
}
