//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molodykh_Potolki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиент()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int код_клиента { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string улица { get; set; }
        public string дом { get; set; }
        public string корпус { get; set; }
        public string квартира { get; set; }
        public string телефон { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
