//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molodykh_Potolki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Потолок
    {
        public int код_потолка { get; set; }
        public int код_марки { get; set; }
        public int код_фактуры { get; set; }
        public Nullable<decimal> цена_метр { get; set; }
    
        public virtual Марка Марка { get; set; }
        public virtual Фактура Фактура { get; set; }
    }
}
